### ISSUE TITLE
it keeps showing 'Firebase: Error (auth/invalid-api-key)' when I try to build it in terminal

### ISSUE THREAD

**Issue by alienmeat** [xJQx/study-gpt#19]
unhandledRejection Error [FirebaseError]: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (file:///Users/apple/study-gpt/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:490:40)
    at _assert (file:///Users/apple/study-gpt/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:494:15)
    at Component.instanceFactory (file:///Users/apple/study-gpt/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:6506:9)
    at Provider.getOrInitializeService (file:///Users/apple/study-gpt/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)
    at Provider.initialize (file:///Users/apple/study-gpt/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)
    at initializeAuth (file:///Users/apple/study-gpt/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:2943:27)
    at getAuth (file:///Users/apple/study-gpt/node_modules/@firebase/auth/dist/node-esm/totp-e47c784e.js:6567:18)
    at /Users/apple/study-gpt/.next/server/chunks/388.js:392:68 {
  type: 'FirebaseError',
  code: 'auth/invalid-api-key',
  customData: { appName: '[DEFAULT]' }
}
- info Collecting page data .%

**Comment by xJQx** [comment]
You are getting this error because your environment variables are not set properly. After cloning the application, you will need to create a `.env` file in your root directory with the fields listed in the `.env.example`.

```env
# .env file with all your environment variables

OPEN_AI_API_KEY=

# Firebase
NEXT_PUBLIC_API_KEY= 
NEXT_PUBLIC_AUTH_DOMAIN= 
NEXT_PUBLIC_PROJECT_ID= 
NEXT_PUBLIC_STORAGE_BUCKET= 
NEXT_PUBLIC_MESSAGING_SENDER_ID= 
NEXT_PUBLIC_APP_ID= 
NEXT_PUBLIC_DATABASE_URL= 

# Firebase google authentication
WEB_CLIENT_ID=
WEB_CLIENT_SECRET=
```

After setting your environment variables, you should be able to build the application with `npm run build` or start it with `npm run dev`.
